spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.19.128
    port: 6379
    password: 123
    client-name: jedis
    jedis:
      pool:
        max-active: 10